const demandesData = [
  {
    typeAcces: "Permanent",
    code: "DA-001",
    nom: "El Amrani",
    prenom: "Samir",
    cin: "Q508674",
    societe: "JESA",
    demandeur: "Khaoula AYOUCH",
    statut: "Validé",
    mission: "Inspection",
    projet: "Projet A",
    dateDebut: "2025-07-01",
    dateFin: "2025-07-02",
    copieCin: null,
    telephone: "0612345678",
    nationalite: "Marocain",
    ficheAnthropometrique: null,
    certificatAptitude: null,
    declarationCNSS: null,
    photoPersonnelle: null,
    listeMateriel: null,
    listePersonnel: null,
    vehicules: [
      { type: "Voiture", marque: "Peugeot", modele: "208", matricule: "5678-CD-90", color: "Bleu", permis: null, papiers: null }
    ],
    acceptTerms: true
  },
  {
    typeAcces: "Provisoir",
    code: "DA-002",
    nom: "Ben Ali",
    prenom: "Yassine",
    cin: "B123456",
    societe: "SEPROB",
    demandeur: "Youness Aniss",
    statut: "En attente",
    approbateur: "Directeur RH",
    mission: "Maintenance",
    projet: "Projet B",
    dateDebut: "2025-07-03",
    dateFin: "2025-07-04",
    copieCin: null,
    telephone: "0623456789",
    nationalite: "Marocain",
    voiture: "Oui",
    cars: [
      { marque: "Renault", modele: "Clio", matricule: "1234-AB-56", color: "Blanc" }
    ],
    apport: "Non",
    objets: [],
    acceptTerms: true
  },
  {
    typeAcces: "Provisoire",
    code: "DA-003",
    nom: "Amine",
    prenom: "Fatima",
    cin: "C987654",
    societe: "AGNV",
    demandeur: "Ahmed Mohammed",
    statut: "Refusé",
    cause: "Document manquant",
    mission: "Audit",
    projet: "Projet C",
    dateDebut: "2025-07-05",
    dateFin: "2025-07-06",
    copieCin: null,
    telephone: "0634567890",
    nationalite: "Marocain",
    voiture: "Non",
    marque: "",
    modele: "",
    matricule: "",
    color: "",
    apport: "Oui",
    objets: [ { objetType: "Ordinateur" } ],
    acceptTerms: true
  },
  {
    typeAcces: "Permanent",
    code: "DA-004",
    nom: "El Idrissi",
    prenom: "Fatima",
    cin: "D456789",
    societe: "JESA",
    demandeur: "Sara Bouzid",
    statut: "Validé",
    mission: "Supervision",
    projet: "Projet D",
    dateDebut: "2025-07-07",
    dateFin: "2025-07-08",
    copieCin: null,
    telephone: "0645678901",
    nationalite: "Marocain",
    ficheAnthropometrique: null,
    certificatAptitude: null,
    declarationCNSS: null,
    photoPersonnelle: null,
    listeMateriel: null,
    listePersonnel: null,
    vehicules: [],
    acceptTerms: true
  },
  {
    typeAcces: "Provisoire",
    code: "DA-005",
    nom: "Kabbaj",
    prenom: "Nadia",
    cin: "E654321",
    societe: "SEPROB",
    demandeur: "Mohamed El Fassi",
    statut: "En attente",
    approbateur: "Directeur RH",
    mission: "Visite",
    projet: "Projet E",
    dateDebut: "2025-07-09",
    dateFin: "2025-07-10",
    copieCin: null,
    telephone: "0656789012",
    nationalite: "Marocain",
    voiture: "Non",
    cars: [],
    apport: "Non",
    objets: [],
    commentaire: "",
    acceptTerms: true
  },
  {
    typeAcces: "Permanent",
    code: "DA-006",
    nom: "Benjelloun",
    prenom: "Karim",
    cin: "F321654",
    societe: "AGNV",
    demandeur: "Fatima Zahra",
    statut: "Refusé",
    cause: "Non respect des consignes",
    mission: "Sécurité",
    projet: "Projet F",
    dateDebut: "2025-07-11",
    dateFin: "2025-07-12",
    copieCin: null,
    telephone: "0667890123",
    nationalite: "Marocain",
    ficheAnthropometrique: null,
    certificatAptitude: null,
    declarationCNSS: null,
    photoPersonnelle: null,
    listeMateriel: null,
    listePersonnel: null,
    vehicules: [],
    acceptTerms: true
  },
  {
    typeAcces: "Provisoire",
    code: "DA-007",
    nom: "El Alaoui",
    prenom: "Sofia",
    cin: "G789123",
    societe: "JESA",
    demandeur: "Othman El Mansouri",
    statut: "Validé",
    mission: "Audit",
    projet: "Projet G",
    dateDebut: "2025-07-13",
    dateFin: "2025-07-14",
    copieCin: null,
    telephone: "0678901234",
    nationalite: "Marocain",
    voiture: "Oui",
    cars: [ { marque: "Peugeot", modele: "208", matricule: "5678-CD-90", color: "Bleu" } ],
    apport: "Oui",
    objets: [ { objetType: "Laptop" } ],
    acceptTerms: true
  },
  {
    typeAcces: "Permanent",
    code: "DA-008",
    nom: "El Ghazali",
    prenom: "Hassan",
    cin: "H987321",
    societe: "SEPROB",
    demandeur: "Imane El Idrissi",
    statut: "En attente",
    approbateur: "Directeur RH",
    mission: "Maintenance",
    projet: "Projet H",
    dateDebut: "2025-07-15",
    dateFin: "2025-07-16",
    copieCin: null,
    telephone: "0689012345",
    nationalite: "Marocain",
    ficheAnthropometrique: null,
    certificatAptitude: null,
    declarationCNSS: null,
    photoPersonnelle: null,
    listeMateriel: null,
    listePersonnel: null,
    vehicules: [],
    acceptTerms: true
  },
  {
    typeAcces: "Provisoire",
    code: "DA-009",
    nom: "El Amrani",
    prenom: "Meryem",
    cin: "I654987",
    societe: "AGNV",
    demandeur: "Youssef Benali",
    statut: "Refusé",
    cause: "Erreur d'identité",
    mission: "Contrôle",
    projet: "Projet I",
    dateDebut: "2025-07-17",
    dateFin: "2025-07-18",
    copieCin: null,
    telephone: "0690123456",
    nationalite: "Marocain",
    voiture: "Non",
    cars: [],
    apport: "Non",
    objets: [],
    acceptTerms: true
  },
  {
    typeAcces: "Permanent",
    code: "DA-010",
    nom: "El Fassi",
    prenom: "Rachid",
    cin: "J123789",
    societe: "JESA",
    demandeur: "Salma Bouzid",
    statut: "Validé",
    mission: "Direction",
    projet: "Projet J",
    dateDebut: "2025-07-19",
    dateFin: "2025-07-20",
    copieCin: null,
    telephone: "0612345678",
    nationalite: "Marocain",
    ficheAnthropometrique: null,
    certificatAptitude: null,
    declarationCNSS: null,
    photoPersonnelle: null,
    listeMateriel: null,
    listePersonnel: null,
    vehicules: [],
    acceptTerms: true
  }
];

export default demandesData;
